# https://docs.helix-editor.com/configuration.html

theme = "monokai_aqua_dark"

[editor]
bufferline = "multiple"
cursorline = true
# gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
line-number = "absolute"
rulers = [120]
auto-completion = true
auto-format = true
auto-save = false
preview-completion-insert = true
auto-info = true
true-color = true
auto-pairs = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "┊" # options:  ▏  ╎  ┆  ┊  ⸽
skip-levels = 1

# [editor.auto-pairs]
# '(' = ')'
# '{' = '}'
# '[' = ']'
# '"' = '"'
# ''' = ''' #?
# '`' = '`'

()[]{}""''``
[editor.statusline]
left = ["mode", "spinner"]
center = ["version-control", "file-absolute-path", "file-modification-indicator"]
# mode.normal="NORMAL"
# mode.insert="INSERT"
# mode.select="SELECT"

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true


[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
# wrap-indicator = ""  # set wrap-indicator to "" to hide it
